# Generated by Django 4.0 on 2021-12-10 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_clientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientesMascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.clientes')),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascotas')),
            ],
            options={
                'db_table': 'clientes_mascotas',
            },
        ),
    ]
