# Generated by Django 4.0 on 2021-12-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_ventas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientesmascotas',
            old_name='id_cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='clientesmascotas',
            old_name='id_mascota',
            new_name='mascota',
        ),
        migrations.RenameField(
            model_name='ventas',
            old_name='id_producto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='ventas',
            old_name='id_servicio',
            new_name='servicio',
        ),
    ]
