# Generated by Django 4.0 on 2021-12-10 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_rename_id_cliente_clientesmascotas_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mascotas.clientes'),
        ),
        migrations.DeleteModel(
            name='ClientesMascotas',
        ),
    ]
