# Generated by Django 4.0 on 2021-12-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0007_remove_mascotas_amo_remove_mascotas_amo_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='producto',
        ),
        migrations.AddField(
            model_name='ventas',
            name='producto',
            field=models.ManyToManyField(blank=True, to='mascotas.Productos'),
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='servicio',
        ),
        migrations.AddField(
            model_name='ventas',
            name='servicio',
            field=models.ManyToManyField(blank=True, to='mascotas.Servicios'),
        ),
    ]
