# Generated by Django 4.0 on 2021-12-12 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0008_remove_ventas_producto_ventas_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('total', models.FloatField()),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mascotas.productos')),
            ],
            options={
                'db_table': 'detalles',
            },
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='servicio',
        ),
        migrations.AddField(
            model_name='ventas',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mascotas.clientes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventas',
            name='detalle',
            field=models.ManyToManyField(blank=True, through='mascotas.Detalles', to='mascotas.Productos'),
        ),
        migrations.AddField(
            model_name='detalles',
            name='venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mascotas.ventas'),
        ),
    ]
