# Generated by Django 4.0 on 2021-12-12 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0009_detalles_remove_ventas_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalles',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mascotas.servicios'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mascotas.clientes'),
        ),
    ]
