# Generated by Django 4.0 on 2021-12-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0011_rename_detalle_ventas_productos_ventas_servicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='productos', through='mascotas.Detalles', to='mascotas.Productos'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='servicios', through='mascotas.Detalles', to='mascotas.Servicios'),
        ),
    ]
